#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/9636a180b67df33196eb8f00f33510a028873aadd78aef8d9dd88d146aefeb41/contract';
import endContract from '../../snapshots/9636a180b67df33196eb8f00f33510a028873aadd78aef8d9dd88d146aefeb41/contract.json' with { type: 'json' };
import type { Contract as Start } from '../../snapshots/a3025b17bc2a7f4b33a262e2278d844ebb037c87b889c7594c7af5f45a271712/contract';
import startContract from '../../snapshots/a3025b17bc2a7f4b33a262e2278d844ebb037c87b889c7594c7af5f45a271712/contract.json' with { type: 'json' };
import { Migration, MigrationCLI } from '@prisma/orm-postgres/migration';

export default class M extends Migration<Start, End> {
  override readonly startContractJson = startContract;
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.enableRowLevelSecurity({ schema: 'public', table: 'address' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'adminAuditLog' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'cart' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'cartItem' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'checkoutRequest' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'delivery' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'favorite' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'kitchenFavorite' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'menuCategory' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'menuItem' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'menuItemOption' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'newsletterSubscriber' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'notification' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'order' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'orderItem' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'orderStatusEvent' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'passwordResetToken' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'payment' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'review' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'rider' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'scheduledMeal' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'scheduledMealEvent' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'shop' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'subscription' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'subscriptionPlan' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'subscriptionPlanItem' }),
      this.enableRowLevelSecurity({ schema: 'public', table: 'user' }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'address',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'address',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'adminAuditLog',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'adminAuditLog',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'cart',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'cart',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'cartItem',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'cartItem',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'checkoutRequest',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'checkoutRequest',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'delivery',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'delivery',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'favorite',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'favorite',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'kitchenFavorite',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'kitchenFavorite',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'menuCategory',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'menuCategory',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'menuItem',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'menuItem',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'menuItemOption',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'menuItemOption',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'newsletterSubscriber',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'newsletterSubscriber',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'notification',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'notification',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'order',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'order',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'orderItem',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'orderItem',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'orderStatusEvent',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'orderStatusEvent',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'passwordResetToken',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'passwordResetToken',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'payment',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'payment',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'review',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'review',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'rider',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'rider',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'scheduledMeal',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'scheduledMeal',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'scheduledMealEvent',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'scheduledMealEvent',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'shop',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'shop',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'subscription',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'subscription',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'subscriptionPlan',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'subscriptionPlan',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'subscriptionPlanItem',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'subscriptionPlanItem',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
      this.createRlsPolicy({
        schema: 'public',
        table: 'user',
        policy: {
          naming: { kind: 'exact', name: 'homefoods_server_only' },
          tableName: 'user',
          namespaceId: 'public',
          operation: 'all',
          roles: ['anon', 'authenticated'],
          using: 'false',
          withCheck: 'false',
          permissive: false,
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
