"use client";
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import KitchenCard from './kitchen-card';
import {filterKitchens,kitchenCollections,type Kitchen} from '@/src/lib/kitchen-discovery';
export default function KitchenDiscovery(){
 const router=useRouter();const [shops,setShops]=useState<Kitchen[]>([]),[saved,setSaved]=useState<number[]>([]),[role,setRole]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState<number|null>(null);
 const [filters,setFilters]=useState({query:'',cuisine:'',collection:'',sort:'',quick:false,free:false});
 useEffect(()=>{const sync=()=>setFilters(f=>({...f,collection:new URLSearchParams(location.search).get('collection')??''}));sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
 useEffect(()=>{const controller=new AbortController();void Promise.all([fetch('/api/catalog',{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setShops(d.shops??[]);}),fetch('/api/auth',{signal:controller.signal}).then(r=>r.json()).then(async d=>{setRole(d.user?.role??'');if(d.user?.role==='CUSTOMER'){const r=await fetch('/api/favorites',{signal:controller.signal});const data=await r.json();if(r.ok)setSaved((data.favoriteKitchens??[]).map((f:{shopId:number})=>f.shopId));}})]).catch(e=>{if(!controller.signal.aborted)setError(e.message||'Kitchens could not be loaded.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
 async function favorite(shop:Kitchen){if(!role){router.push('/signin?returnTo=%2Fkitchens');return;}if(role!=='CUSTOMER'){setNotice('Kitchen favourites are available with a customer account.');return;}if(pending!==null)return;setPending(shop.id);setNotice('');try{const r=await fetch('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({shopId:shop.id})});const d=await r.json();if(!r.ok)throw Error(d.error);setSaved(old=>old.includes(shop.id)?old.filter(id=>id!==shop.id):[...old,shop.id]);window.dispatchEvent(new Event('homefoods:favorites-change'));localStorage.setItem('homefoods:favorites-updated',String(Date.now()));}catch(e){setNotice(e instanceof Error?e.message:'Could not update favourites.');}finally{setPending(null);}}
 function collection(value:string){setFilters(f=>({...f,collection:value,sort:''}));history.pushState(null,'',value?`/kitchens?collection=${encodeURIComponent(value)}`:'/kitchens');}
 const result=filterKitchens(shops,filters),cuisines=[...new Set(shops.map(s=>s.cuisine).filter((s):s is string=>!!s))].sort();
 return <main id="main-content" tabIndex={-1} className="kitchen-discovery"><header className="discovery-heading"><span className="eyebrow">COOKS, NEIGHBOURS & GOOD FOOD</span><h1>Explore Kitchens</h1><p>Find your next favourite home cook. Discover homemade food from kitchens throughout Finland.</p></header>
 <section className="kitchen-discovery-tools" aria-label="Find a kitchen"><label className="discovery-query">Search kitchens<input type="search" value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})} placeholder="Kitchen, cuisine or city"/></label><label>Cuisine<select value={filters.cuisine} onChange={e=>setFilters({...filters,cuisine:e.target.value})}><option value="">All cuisines</option>{cuisines.map(c=><option key={c}>{c}</option>)}</select></label><label>Sort by<select value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})}><option value="">Recommended</option><option value="rating">Highest rated</option><option value="popular">Most ordered</option><option value="newest">Newest</option><option value="quick">Preparation time</option><option value="fee">Delivery fee</option></select></label><label className="discovery-check"><input type="checkbox" checked={filters.quick} onChange={e=>setFilters({...filters,quick:e.target.checked})}/>30 minutes or less</label><label className="discovery-check"><input type="checkbox" checked={filters.free} onChange={e=>setFilters({...filters,free:e.target.checked})}/>Free delivery</label></section>
 <nav className="app-section-nav" aria-label="Kitchen collections"><button aria-pressed={!filters.collection} onClick={()=>collection('')}>All kitchens</button>{Object.entries(kitchenCollections).filter(([key])=>filterKitchens(shops,{...filters,query:'',cuisine:'',quick:false,free:false,collection:key}).length>0).map(([key,title])=><button key={key} aria-pressed={filters.collection===key} onClick={()=>collection(key)}>{title}</button>)}</nav>
 {notice&&<p role="status" className="workspace-notice">{notice}</p>}{loading?<div className="discovery-loading" role="status">Finding kitchens…</div>:error?<div role="alert" className="workspace-alert">{error}<button onClick={()=>location.reload()}>Try again</button></div>:<><div className="discovery-result-heading"><h2>{kitchenCollections[filters.collection as keyof typeof kitchenCollections]??'Kitchens to discover'}</h2><p role="status">{result.length} {result.length===1?'kitchen':'kitchens'} · accepting orders</p></div>{result.length?<div className="kitchen-discovery-grid" aria-busy={pending!==null}>{result.map(shop=><KitchenCard key={shop.id} shop={shop} saved={saved.includes(shop.id)} onFavoriteShop={favorite}/>)}</div>:<div className="discovery-empty"><h2>No kitchens match these filters</h2><p>Try another cuisine, city or delivery preference.</p><button onClick={()=>{setFilters({query:'',cuisine:'',collection:'',sort:'',quick:false,free:false});history.pushState(null,'','/kitchens');}}>Clear filters</button></div>}</>}
 </main>;
}
