"use client";
import {useEffect,useState,type FormEvent} from 'react';
import ImageUpload from './image-upload';
import AddressEditor from './address-editor';
import MarketImage from './market-image';
import NavigationIcon from './navigation-icon';
import {kitchenProfileError} from '@/src/lib/kitchen-profile';
type Row=Record<string,unknown>;
const text=(v:unknown)=>String(v??'');
export default function KitchenSettings({shop,onSaved}:{shop:Row;onSaved:()=>Promise<void>}){
 const complete=!!shop.profileCompletedAt,verified=shop.locationIsVerified===true;
 const [profileOpen,setProfileOpen]=useState(!complete),[addressOpen,setAddressOpen]=useState(!verified),[profileDirty,setProfileDirty]=useState(false),[addressDirty,setAddressDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{if(!profileDirty&&!addressDirty)return;const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();};const click=(e:MouseEvent)=>{const a=(e.target as Element)?.closest('a');if(a?.href&&new URL(a.href).pathname!==location.pathname&&!window.confirm('Leave without saving your kitchen changes?')){e.preventDefault();e.stopPropagation();}};const signout=(e:Event)=>{if(!window.confirm('Sign out without saving your kitchen changes?'))e.preventDefault();};window.addEventListener('homefoods:before-signout',signout);window.addEventListener('beforeunload',unload);document.addEventListener('click',click,true);return()=>{window.removeEventListener('homefoods:before-signout',signout);window.removeEventListener('beforeunload',unload);document.removeEventListener('click',click,true);};},[profileDirty,addressDirty]);
 async function save(body:Row){setBusy(true);setError('');try{const r=await fetch('/api/seller',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error??'Could not save. Your changes are still here.');await onSaved();}catch(e){setError(e instanceof Error?e.message:'Could not save.');throw e;}finally{setBusy(false);}}
 async function profileSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={action:'save-profile',...Object.fromEntries(f),deliveryFee:Number(f.get('deliveryFee')),estimatedMinutes:Number(f.get('estimatedMinutes'))};const invalid=kitchenProfileError(body);if(invalid){setError(invalid);return;}try{await save(body);setProfileDirty(false);setProfileOpen(false);setNotice('Kitchen profile saved.');}catch{}}
 const postal=text(shop.address).match(/\b\d{5}\b/)?.[0]??'';
 const initial={addressLine1:text(shop.address).split(',')[0].replace(/^\[SANDBOX LOCATION\]\s*/,''),city:text(shop.city),postalCode:postal,countryCode:'FI',latitude:typeof shop.latitude==='number'?shop.latitude:null,longitude:typeof shop.longitude==='number'?shop.longitude:null};
 return <section id="kitchen-settings" className={`kitchen-settings ${complete&&verified?'is-complete':'needs-setup'}`}>
 <div className="workspace-section-heading"><div><span className="eyebrow">YOUR KITCHEN, YOUR DETAILS</span><h2>{complete&&verified?'Kitchen Settings':'Complete your kitchen setup'}</h2><p>{complete&&verified?'Everything is saved. Update your details whenever you need to.':'Confirm your profile and Finnish pickup address. Your operational tools remain available below.'}</p></div><span className="status-pill">{Number(complete)+Number(verified)} / 2 completed</span></div>
 {notice&&<p role="status" className="workspace-notice">{notice}</p>}{error&&<p role="alert" className="workspace-alert">{error}</p>}
 <article className="kitchen-setting-card"><button className="kitchen-setting-summary" aria-expanded={profileOpen} aria-controls="kitchen-profile-fields" onClick={()=>setProfileOpen(!profileOpen)}><span className="setting-icon">{shop.logoUrl?<MarketImage src={text(shop.logoUrl)} alt="" fallbackSrc="/favicon.ico"/>:<NavigationIcon name="kitchen"/>}</span><span><strong>Kitchen Profile</strong><span>{text(shop.name)}{shop.description?` · ${text(shop.description).slice(0,100)}`:''}</span>{shop.phone?<small>{text(shop.phone)}</small>:null}<small>{profileDirty?'Unsaved changes':complete?'Profile completed':'Action required · confirm and save your details'}</small></span><b>{profileOpen?'Collapse':'Edit'}</b></button>
 <div id="kitchen-profile-fields" hidden={!profileOpen} className="kitchen-setting-body"><form className="workspace-form" onSubmit={profileSubmit} onChange={()=>setProfileDirty(true)}>
 <label>Kitchen name<input name="name" required minLength={2} maxLength={100} defaultValue={text(shop.name)}/></label><label>About your food<input name="description" maxLength={1200} defaultValue={text(shop.description)}/></label><label>Contact phone<input name="phone" maxLength={40} defaultValue={text(shop.phone)}/></label><ImageUpload name="logoUrl" label="Kitchen logo" initialValue={text(shop.logoUrl)} disabled={busy}/><ImageUpload name="coverImageUrl" label="Kitchen cover image" initialValue={text(shop.coverImageUrl)} disabled={busy}/><label>Delivery fee (€)<input required name="deliveryFee" type="number" step="0.01" min="0" max="50" defaultValue={text(shop.deliveryFee??0)}/></label><label>Prep time (minutes)<input required name="estimatedMinutes" type="number" step="1" min="10" max="240" defaultValue={text(shop.estimatedMinutes??35)}/></label><button className="dark-cta" disabled={busy}>{busy?'Saving…':'Save kitchen profile'}</button><small>Images are optional. Confirm each upload, then save your profile. Collapsing this card keeps your unsaved edits.</small></form></div></article>
 <article className="kitchen-setting-card"><button className="kitchen-setting-summary" aria-expanded={addressOpen} aria-controls="kitchen-address-fields" onClick={()=>setAddressOpen(!addressOpen)}><span className="setting-icon"><NavigationIcon name="home"/></span><span><strong>Kitchen Address</strong><span>{text(shop.address)||'Choose your Finnish pickup address'}</span><small>{addressDirty?'Changes need verification':verified?'Verified Finnish address':'Action required · verify your location'}</small></span><b>{addressOpen?'Collapse':'Edit Address'}</b></button>
 <div id="kitchen-address-fields" hidden={!addressOpen} className="kitchen-setting-body"><p>Confirm the street and building. Existing orders keep their original pickup details.</p><AddressEditor initial={initial} saveToAccount={false} onDirtyChange={()=>setAddressDirty(true)} onSaved={async address=>{await save({action:'set-location',verificationToken:address.verificationToken,address:`${address.addressLine1}, ${address.postalCode} ${address.city}, Finland`});setAddressDirty(false);setAddressOpen(false);setNotice('Kitchen address verified and saved.');}}/></div></article>
 </section>;
}
