"use client";
import { useCallback, useEffect, useState } from "react";
type Health={provider:{status:string;message:string;checkedAt:string};radiusEnforced:boolean;kitchens:Array<{id:number;name:string;address:string|null;city:string|null;status:string;locationStatus:string}>};
export default function LocationHealth(){
  const [data,setData]=useState<Health|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=useCallback(async()=>{setBusy(true);setError('');try{const response=await fetch('/api/admin/health',{cache:'no-store',signal:AbortSignal.timeout(45000)});const value=await response.json();if(!response.ok)throw Error(value.error);setData(value);}catch(e){setError(e instanceof Error?e.message:'Health check failed.');}finally{setBusy(false);}},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  const attention=data?.kitchens.filter(k=>k.status==='ACTIVE'&&k.locationStatus!=='stored')??[];
  return <section className="location-health workspace-card" aria-labelledby="location-health-title"><header><div><span className="eyebrow">LOCATION OPERATIONS</span><h2 id="location-health-title">Address service health</h2></div><button type="button" disabled={busy} onClick={()=>void load()}>{busy?'Checking…':'Check again'}</button></header>{error&&<p className="form-error" role="alert">{error}</p>}{data&&<><p className={data.provider.status==='ready'?'health-ready':'health-warning'} role="status"><b>{data.provider.status==='ready'?'Geoapify connected':'Address service needs attention'}</b><span>{data.provider.message}</span></p><small>Last provider check: {new Date(data.provider.checkedAt).toLocaleString('fi-FI')}. Checks are cached for two minutes.</small><p><b>Delivery radius: {data.radiusEnforced?'enforced':'disabled for development'}</b>. This panel does not change delivery settings.</p><h3>{attention.length} active kitchens need location attention</h3>{attention.length?<ul>{attention.map(k=><li key={k.id}><div><b>{k.name}</b><span>{k.address??'No street address saved'}</span></div><strong>{k.locationStatus==='example'?'Development example':'Missing location'}</strong></li>)}</ul>:<p>Active kitchens have stored locations. Their Finnish coordinates are validated during checkout.</p>}</>}{!data&&!error&&<p role="status">Checking provider access and kitchen configuration…</p>}</section>;
}
