'use client';
import type {ModifierGroup} from '@/src/lib/modifiers';
export default function ModifierEditor({groups,onChange,disabled}:{groups:ModifierGroup[];onChange:(groups:ModifierGroup[])=>void;disabled:boolean}){
  const update=(id:string,patch:Partial<ModifierGroup>)=>onChange(groups.map(g=>g.id===id?{...g,...patch}:g));
  return <fieldset className="modifier-editor" disabled={disabled}><legend>Extras &amp; Customizations</legend><p>Optional extras and preferences, separate from portion sizes.</p>
    {groups.map(g=><details key={g.id} className="modifier-group" open><summary>{g.name||'New group'} <small>{g.required?'Required':'Optional'} · {g.options.length} options</small></summary><div className="seller-dish-fields">
      <label>Group name<input value={g.name} required maxLength={80} onChange={e=>update(g.id,{name:e.target.value})}/></label>
      <label>Choice type<select value={g.multiple?'multiple':'single'} onChange={e=>update(g.id,{multiple:e.target.value==='multiple',max:e.target.value==='single'?1:Math.max(g.max,3),min:g.required?1:0})}><option value="single">Single choice</option><option value="multiple">Multiple choices</option></select></label>
      <label className="seller-availability"><input type="checkbox" checked={g.required} onChange={e=>update(g.id,{required:e.target.checked,min:e.target.checked?1:0})}/>Required</label>
      {g.multiple&&<><label>Minimum selections<input type="number" min={g.required?1:0} max={20} disabled={!g.required} value={g.min} onChange={e=>update(g.id,{min:Number(e.target.value)})}/></label><label>Maximum selections<input type="number" min={1} max={20} value={g.max} onChange={e=>update(g.id,{max:Number(e.target.value)})}/></label></>}
    </div><div className="modifier-options">{g.options.map(o=><div className="modifier-option-editor" key={o.id}><label>Option name<input required maxLength={80} value={o.name} onChange={e=>update(g.id,{options:g.options.map(v=>v.id===o.id?{...v,name:e.target.value}:v)})}/></label><label>Extra price (€)<input type="number" min={0} max={500} step="0.01" required value={o.price} onChange={e=>update(g.id,{options:g.options.map(v=>v.id===o.id?{...v,price:Number(e.target.value)}:v)})}/></label><label className="seller-availability"><input type="checkbox" checked={o.isAvailable} onChange={e=>update(g.id,{options:g.options.map(v=>v.id===o.id?{...v,isAvailable:e.target.checked}:v)})}/>Available</label><button type="button" aria-label={`Remove ${o.name||'option'}`} onClick={()=>update(g.id,{options:g.options.filter(v=>v.id!==o.id)})}>Remove</button></div>)}</div>
      <div className="workspace-actions"><button type="button" disabled={g.options.length>=20} onClick={()=>update(g.id,{options:[...g.options,{id:crypto.randomUUID(),name:'',price:0,isAvailable:true}]})}>+ Add option</button><button type="button" onClick={()=>onChange(groups.filter(v=>v.id!==g.id))}>Remove group</button></div>
    </details>)}<button type="button" disabled={groups.length>=10} onClick={()=>onChange([...groups,{id:crypto.randomUUID(),name:'',required:false,multiple:true,min:0,max:3,options:[{id:crypto.randomUUID(),name:'',price:0,isAvailable:true}]}])}>+ Add group</button>
  </fieldset>;
}
