"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import OverlayLayer from './overlay-layer';
type Notice={id:number;title:string;message:string;createdAt:string;readAt:string|null;href:string;kind:string};
export default function OrderNotifications({userId}:{userId:number}){
 const dialog=useRef<HTMLElement|null>(null),trigger=useRef<HTMLButtonElement|null>(null),known=useRef<Set<number>|null>(null);
 const [items,setItems]=useState<Notice[]>([]),[count,setCount]=useState(0),[open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pulse,setPulse]=useState(false),[loading,setLoading]=useState(true);
 const refresh=useCallback(async(signal?:AbortSignal)=>{try{const r=await fetch('/api/notifications',{cache:'no-store',signal});const data=await r.json();if(!r.ok)throw Error(data.error);if(signal?.aborted)return;const next:Notice[]=data.notifications;if(known.current&&next.some(n=>!n.readAt&&!known.current!.has(n.id)))setPulse(true);known.current=new Set(next.map(n=>n.id));setItems(next);setCount(data.unreadCount);setError('');}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Could not refresh.');}finally{if(!signal?.aborted)setLoading(false);}},[]);
 useEffect(()=>{const controller=new AbortController();let inFlight=false;const update=async()=>{if(document.hidden||inFlight)return;inFlight=true;await refresh(controller.signal);inFlight=false;};void update();const timer=setInterval(()=>void update(),20000);window.addEventListener('focus',update);document.addEventListener('visibilitychange',update);window.addEventListener('homefoods:notifications-change',update);return()=>{controller.abort();clearInterval(timer);window.removeEventListener('focus',update);document.removeEventListener('visibilitychange',update);window.removeEventListener('homefoods:notifications-change',update);};},[userId,refresh]);
 async function mark(id?:number){setBusy(true);try{const r=await fetch('/api/notifications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(id?{id}:{all:true})});const d=await r.json();if(!r.ok)throw Error(d.error);await refresh();window.dispatchEvent(new Event('homefoods:notifications-change'));return true;}catch(e){setError(e instanceof Error?e.message:'Could not save read status.');return false;}finally{setBusy(false);}}
 return <><button ref={trigger} className={`header-notifications ${pulse?'has-new':''}`} onAnimationEnd={()=>setPulse(false)} onClick={()=>{setOpen(true);void refresh();}} aria-label={`Notifications${count?', '+count+' unread':''}`} aria-expanded={open} aria-haspopup="dialog"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5l-2 3Zm5 3h4"/></svg>{count>0&&<b>{count>99?'99+':count}</b>}</button>
 <OverlayLayer open={open} onClose={()=>setOpen(false)} label="Notifications" className="modal-backdrop account-notification-overlay" dialogClassName="account-notification-panel" dialogRef={dialog} triggerRef={trigger} dismissOnBackdrop><header><div><span className="eyebrow">YOUR HOMEFOODS</span><h2>Notifications</h2><p role="status">{count} unread</p></div><button className="close-button" aria-label="Close notifications" onClick={()=>setOpen(false)}>×</button></header>
 {error&&<div role="alert" className="workspace-alert">{error}<button onClick={()=>void refresh()}>Retry</button></div>}
 {loading?<p role="status">Loading notifications…</p>:items.length?<><button disabled={busy||count===0} onClick={()=>void mark()}>Mark All as Read</button><ul>{items.map(n=><li key={n.id} data-unread={!n.readAt}><span className="notification-kind" aria-hidden="true">{n.kind==='alert'?'!':n.kind==='order'?'◷':'♧'}</span><div><Link href={n.href} onClick={event=>{if(n.href.split('#')[0]===location.pathname&&n.href.includes('#')){event.preventDefault();location.hash=n.href.split('#')[1];}if(!n.readAt)void mark(n.id);setOpen(false);}}><strong>{n.title}</strong><p>{n.message}</p><time dateTime={n.createdAt}>{new Date(n.createdAt).toLocaleString()}</time></Link>{!n.readAt&&<button disabled={busy} onClick={()=>void mark(n.id)}>Mark as Read</button>}<small>{n.readAt?'Read':'Unread'}</small></div></li>)}</ul><p>Showing the latest {items.length} updates. Checks for new notifications every 20 seconds while this page is visible.</p></>:<div className="notification-empty"><span aria-hidden="true">♧</span><h3>You’re all caught up!</h3><p>Your next HomeFoods update will appear here.</p></div>}</OverlayLayer></>;
}
