'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
type Row=Record<string,unknown>;
export default function PersonalMealPlans(){
 const [plans,setPlans]=useState<Row[]>([]),[subscriptions,setSubscriptions]=useState<Row[]>([]),[addresses,setAddresses]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[cancel,setCancel]=useState<number|null>(null);
 const load=useCallback(async()=>{try{const [p,a]=await Promise.all([fetch('/api/subscriptions',{cache:'no-store'}),fetch('/api/addresses',{cache:'no-store'})]);const pd=await p.json(),ad=await a.json();if(!p.ok||!a.ok)throw Error(pd.error??ad.error);setPlans(pd.plans??[]);setSubscriptions(pd.subscriptions??[]);setAddresses(ad.addresses??[]);}catch(e){setError(e instanceof Error?e.message:'Could not load plans.');}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
 async function send(body:Row,method:string){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/subscriptions',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw Error(data.error);if(data.checkoutUrl){window.location.assign(data.checkoutUrl);return;}setNotice('Meal plan updated.');setCancel(null);await load();}catch(e){setError(e instanceof Error?e.message:'Could not update plan.');}finally{setBusy(false);}}
 function subscribe(e:FormEvent<HTMLFormElement>,planId:number){e.preventDefault();const form=new FormData(e.currentTarget);void send({planId,addressId:Number(form.get('addressId')),startDate:form.get('startDate'),portions:Number(form.get('portions')),deliveryTime:form.get('deliveryTime')},'POST');}
 return <section id="plans" className="workspace-section personal-meal-plans"><h2>Manage your meal plans</h2>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {subscriptions.map(s=><article className="workspace-card" key={String(s.id)}><h3>{String((s.plan as Row)?.name??'Meal plan')}</h3><p>{String(s.status)}</p>{s.status!=='CANCELLED'&&<div className="workspace-actions"><button disabled={busy} onClick={()=>void send({subscriptionId:s.id,action:s.status==='PAUSED'?'resume':'pause'},'PATCH')}>{s.status==='PAUSED'?'Resume':'Pause'}</button><button disabled={busy} onClick={()=>setCancel(Number(s.id))}>Cancel plan</button>{cancel===s.id&&<div role="alert"><p>Stop future renewals for this plan?</p><button disabled={busy} onClick={()=>void send({subscriptionId:s.id,action:'cancel'},'PATCH')}>Confirm cancellation</button><button onClick={()=>setCancel(null)}>Keep plan</button></div>}</div>}</article>)}
 <h2>Meal plans from home cooks</h2>{!addresses.length&&<p><Link href="/account#addresses">Add a delivery address</Link> before subscribing.</p>}<div className="plan-grid">{plans.map(plan=><article id={`plan-${String(plan.id)}`} key={String(plan.id)} className="workspace-card"><h3>{String(plan.name)}</h3><p>{String(plan.description??'')}</p><b>{new Intl.NumberFormat('fi-FI',{style:'currency',currency:'EUR'}).format(Number(plan.price))} / {String(plan.type).toLowerCase()}</b><form className="workspace-form" onSubmit={e=>subscribe(e,Number(plan.id))}><label>Delivery address<select name="addressId" required defaultValue=""><option value="" disabled>Choose a saved address</option>{addresses.map(a=><option key={String(a.id)} value={String(a.id)}>{String(a.label??a.addressLine1)} — {String(a.city)}</option>)}</select></label><label>Start date<input type="date" name="startDate" required/></label><label>Portions<input type="number" name="portions" min="1" max="20" defaultValue="1"/></label><label>Delivery time<input type="time" name="deliveryTime" defaultValue="12:00"/></label><button className="dark-cta" disabled={busy||!addresses.length||Boolean(plan.isOwnKitchen)}>{plan.isOwnKitchen?'Your kitchen':'Subscribe with Stripe →'}</button></form></article>)}</div>
 </section>;
}
