"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import AddressEditor,{addressChanged,addressRequest,type SavedAddress} from "./address-editor";
import OverlayLayer from "./overlay-layer";
export default function SavedAddresses({onChange}:{onChange?:()=>void}){
 const [addresses,setAddresses]=useState<SavedAddress[]>([]),[editing,setEditing]=useState<SavedAddress|null|undefined>(undefined),[removing,setRemoving]=useState<SavedAddress|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const dialog=useRef<HTMLElement|null>(null);
 const refresh=useCallback(async()=>{try{const r=await addressRequest("/api/addresses");setAddresses(r.addresses);}catch(e){setError(e instanceof Error?e.message:"Couldn't load addresses.");}},[]);
 useEffect(()=>{queueMicrotask(()=>void refresh());},[refresh]);
 async function act(body:unknown,method:string,notice:string){setBusy(true);setError("");try{await addressRequest("/api/addresses",body,method);await refresh();setMessage(notice);setRemoving(null);addressChanged();onChange?.();}catch(e){setError(e instanceof Error?e.message:"Couldn't update address.");}finally{setBusy(false);}}
 return <section className="workspace-section" id="addresses"><div className="workspace-section-heading"><div><span className="eyebrow">YOUR FAMILIAR PLACES</span><h2>Saved addresses</h2></div><button type="button" className="address-add" onClick={()=>{setEditing(null);setError("");}}>+ Add address</button></div>
 {message&&<p className="address-note" role="status">{message}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 {editing!==undefined?<div className="address-edit-panel"><h3>{editing?"Edit address":"Add your address"}</h3><AddressEditor key={editing?.id??"new"} initial={editing??undefined} onCancel={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);setMessage("Address saved.");void refresh();onChange?.();}}/></div>:addresses.length?<div className="saved-address-grid">{addresses.map(a=><article className="saved-address-card" key={a.id}><div className="saved-address-title"><span aria-hidden="true">⌖</span><h3>{a.label||"Delivery address"}</h3>{a.isDefault&&<span className="address-badge">Default</span>}</div><p>{a.addressLine1}<br/>{a.addressLine2&&<>{a.addressLine2}<br/></>}{a.postalCode} {a.city}<br/>Finland</p><small>{a.status==="verified"?"Verified Finnish address":a.status==="sandbox"?"Sandbox only · not verified for real delivery":"Verification needed before ordering"}</small><div className="saved-address-actions"><button type="button" onClick={()=>setEditing(a)}>Edit</button>{!a.isDefault&&<button type="button" disabled={busy} onClick={()=>void act({id:a.id,action:"default"},"PATCH","Default address updated.")}>Set as default</button>}<button type="button" className="address-remove" onClick={()=>setRemoving(a)}>Delete</button></div></article>)}</div>:<div className="address-empty"><span aria-hidden="true">⌂</span><h3>A place for your next meal</h3><p>Save your first Finnish address to make checkout easier.</p><button type="button" onClick={()=>setEditing(null)}>Add your first address</button></div>}
 <OverlayLayer open={!!removing} className="modal-backdrop" dialogClassName="address-remove-dialog" dialogRef={dialog} label="Remove this address?" onClose={()=>!busy&&setRemoving(null)}><h2>Remove this address?</h2><p>Are you sure you want to remove this saved address from your account?</p><p>Past orders keep their delivery details. If this is your default, your most recently added remaining address becomes the default.</p><div className="address-actions"><button type="button" onClick={()=>setRemoving(null)} disabled={busy}>Cancel</button><button type="button" disabled={busy} onClick={()=>void act({id:removing?.id},"DELETE","Address removed from your saved places.")}>{busy?"Removing…":"Remove Address"}</button></div></OverlayLayer>
 </section>;
}
