"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import SpotlightCard from "@/src/components/ui/spotlight-card";
import { OriginButton } from "@/src/components/ui/origin-button";

type Row = Record<string, unknown>;
const rows = (value: unknown) => Array.isArray(value) ? value as Row[] : [];
const money = (value: unknown) => new Intl.NumberFormat("fi-FI", { style: "currency", currency: "EUR" }).format(Number(value ?? 0));
const field = (data: FormData, key: string) => String(data.get(key) ?? "").trim();

export default function SellerKitchenEditor({ onSaved }: { onSaved: () => void }) {
  const [shop, setShop] = useState<Row>({});
  const [items, setItems] = useState<Row[]>([]);
  const [categories, setCategories] = useState<Row[]>([]);
  const [plans, setPlans] = useState<Row[]>([]);
  const [subscriptions, setSubscriptions] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [confirm, setConfirm] = useState<{ title: string; action: () => Promise<void> } | null>(null);

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const response = await fetch("/api/seller", { cache: "no-store" });
      const data = await response.json() as Row;
      if (!response.ok) throw new Error(String(data.error ?? "Seller kitchen could not be loaded."));
      setShop(data.shop && typeof data.shop === "object" ? data.shop as Row : {}); setItems(rows(data.items)); setCategories(rows(data.categories)); setPlans(rows(data.plans)); setSubscriptions(rows(data.subscriptions));
    } catch (issue) { setError(issue instanceof Error ? issue.message : "Seller kitchen could not be loaded."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  async function mutate(path: string, method: "POST" | "PATCH" | "DELETE", body: Row, message: string) {
    setBusy(true); setError(""); setNotice("");
    try {
      const response = await fetch(path, { method, headers: method === "DELETE" ? undefined : { "Content-Type": "application/json" }, body: method === "DELETE" ? undefined : JSON.stringify(body) });
      const data = await response.json() as Row;
      if (!response.ok) throw new Error(String(data.error ?? "Couldn't save that change."));
      setNotice(message); await load(); onSaved();
    } catch (issue) { setError(issue instanceof Error ? issue.message : "Couldn't save that change."); }
    finally { setBusy(false); }
  }

  function submit(event: FormEvent<HTMLFormElement>, action: (form: FormData) => Promise<void>) {
    event.preventDefault(); void action(new FormData(event.currentTarget));
  }

  if (loading) return <section className="workspace-section seller-editor" aria-busy="true"><div className="workspace-empty"><span className="loading-spinner"/><h2>Opening your kitchen…</h2><p>Loading your private kitchen, dishes and plans.</p></div></section>;
  if (!shop.id && !error) return <section className="workspace-section seller-editor"><div className="workspace-section-heading"><div><span className="eyebrow">YOUR KITCHEN</span><h2>Set up your kitchen</h2><p>Your seller account is ready. Add the basics now, then finish your Finnish delivery location and menu.</p></div></div>{notice && <p className="workspace-notice" role="status">{notice}</p>}<form className="workspace-form seller-editor-form" onSubmit={(event) => submit(event, (form) => mutate("/api/seller", "POST", { action: "create-kitchen", name: field(form, "name"), description: field(form, "description"), city: field(form, "city") }, "Kitchen created. Add your verified address and dishes to continue."))}><h3>Kitchen details</h3><label>Kitchen name<input name="name" required minLength={2} maxLength={100} placeholder="e.g. Tanvir’s home kitchen"/></label><label>City or town<input name="city" maxLength={80} required placeholder="Helsinki"/></label><label className="seller-kitchen-description">A little about your food<textarea name="description" rows={3} maxLength={1200} placeholder="Tell customers what you love to cook."/></label>{error && <p className="workspace-alert" role="alert">{error}</p>}<OriginButton type="submit" loading={busy} loadingText="Creating…">Create your kitchen <span>→</span></OriginButton><small>New kitchens start as pending review and stay private until approved.</small></form></section>;
  if (error && !shop.id) return <section className="workspace-section seller-editor"><div className="workspace-section-heading"><div><span className="eyebrow">YOUR KITCHEN</span><h2>We couldn’t open this kitchen</h2></div></div><p className="workspace-alert" role="alert">{error}</p><button type="button" onClick={() => void load()}>Try loading again</button></section>;

  return <section className="workspace-section seller-editor" id="seller-menu">
    <div className="workspace-section-heading"><div><span className="eyebrow">KITCHEN OPERATIONS</span><h2>{String(shop.name ?? "Your kitchen")}</h2><p>Changes here apply only to your kitchen.</p></div><span className="status-pill">{String(shop.status ?? "PENDING")}</span></div>
    {error && <p className="workspace-alert" role="alert">{error}</p>}{notice && <p className="workspace-notice" role="status">{notice}</p>}
    <div className="seller-editor-stats"><SpotlightCard className="spotlight-kpi" size="small" glowColor="green"><span>MENU DISHES</span><b>{items.length}</b></SpotlightCard><SpotlightCard className="spotlight-kpi" size="small" glowColor="orange"><span>AVAILABLE NOW</span><b>{items.filter((item) => Boolean(item.isAvailable)).length}</b></SpotlightCard><SpotlightCard className="spotlight-kpi" size="small" glowColor="purple"><span>MEAL PLANS</span><b>{plans.length}</b></SpotlightCard></div>

    <section className="seller-meal-schedule"><div className="workspace-section-heading"><div><span className="eyebrow">PLAN FULFILMENT</span><h3>Scheduled meal deliveries</h3><p>These are paid subscription orders, scheduled in Finland time.</p></div><span>{subscriptions.reduce((total, entry) => total + rows(entry.scheduledMeals).filter((meal) => !["DELIVERED", "CANCELLED", "FAILED"].includes(String(meal.status))).length, 0)} upcoming / active</span></div>{subscriptions.flatMap((subscription) => rows(subscription.scheduledMeals).map((meal) => ({ subscription, meal }))).filter(({ meal }) => !["DELIVERED", "CANCELLED", "FAILED"].includes(String(meal.status))).length ? <div className="workspace-list">{subscriptions.flatMap((subscription) => rows(subscription.scheduledMeals).map((meal) => ({ subscription, meal }))).filter(({ meal }) => !["DELIVERED", "CANCELLED", "FAILED"].includes(String(meal.status))).sort((a, b) => new Date(String(a.meal.scheduledAt)).getTime() - new Date(String(b.meal.scheduledAt)).getTime()).map(({ subscription, meal }) => { const order = (meal.order as Row | undefined) ?? {}; const customer = (subscription.customer as Row | undefined) ?? {}; const plan = (subscription.plan as Row | undefined) ?? {}; return <article className="workspace-card seller-meal-row" key={String(meal.id)}><div><b>{String(plan.name ?? "Meal plan")} · {new Date(String(meal.scheduledAt)).toLocaleString("fi-FI", { timeZone: "Europe/Helsinki", weekday: "short", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}</b><span>{String(customer.name ?? customer.email ?? "Customer")} · Order {String(order.orderNumber ?? "pending")}</span><small>{rows(order.items).map((item) => `${String(item.quantity)} × ${String(item.name)}`).join(" · ") || "Menu is being confirmed"} · {String(meal.portions ?? 1)} portion(s)</small></div><span className="status-pill">{String(meal.status ?? order.status ?? "UPCOMING").replaceAll("_", " ")}</span><button type="button" onClick={() => { window.location.hash = "orders"; document.getElementById("orders")?.scrollIntoView({ behavior: "smooth" }); }}>Manage order</button></article>; })}</div> : <p className="workspace-muted">No paid meal-plan deliveries are scheduled. Future meals will appear here after successful subscription billing.</p>}</section>

    <form className="workspace-form seller-editor-form" onSubmit={(event) => submit(event, (form) => mutate("/api/seller", "PATCH", { name: field(form, "name"), description: field(form, "description"), phone: field(form, "phone"), logoUrl: field(form, "logoUrl"), coverImageUrl: field(form, "coverImageUrl"), deliveryFee: Number(form.get("deliveryFee")), estimatedMinutes: Number(form.get("estimatedMinutes")) }, "Kitchen details saved."))}>
      <h3>Kitchen profile</h3><label>Kitchen name<input name="name" required defaultValue={String(shop.name ?? "")}/></label><label>About your food<input name="description" defaultValue={String(shop.description ?? "")}/></label><label>Contact phone<input name="phone" defaultValue={String(shop.phone ?? "")}/></label><label>Logo image URL<input type="url" name="logoUrl" placeholder="https://…" defaultValue={String(shop.logoUrl ?? "")}/></label><label>Cover image URL<input type="url" name="coverImageUrl" placeholder="https://…" defaultValue={String(shop.coverImageUrl ?? "")}/></label><label>Delivery fee (€)<input name="deliveryFee" type="number" step="0.01" min="0" max="50" defaultValue={String(shop.deliveryFee ?? 0)}/></label><label>Prep time (minutes)<input name="estimatedMinutes" type="number" step="1" min="10" max="240" defaultValue={String(shop.estimatedMinutes ?? 35)}/></label><OriginButton type="submit" loading={busy} loadingText="Saving…">Save kitchen profile <span>→</span></OriginButton><small>Image URLs can be changed here. Image file uploads need an object-storage provider, which is not configured in this project.</small>
    </form>

    <form className="workspace-form seller-editor-form" onSubmit={(event) => submit(event, (form) => mutate("/api/seller", "PATCH", { action: "set-location", address: field(form, "address") }, "Finnish kitchen location verified and saved."))}>
      <h3>Delivery location</h3><label>Finnish kitchen address<input name="address" required minLength={5} defaultValue={String(shop.address ?? "")} placeholder="Street, postal code, city, Finland"/></label><OriginButton type="submit" variant="secondary" loading={busy} loadingText="Verifying…">Verify and save location <span>⌖</span></OriginButton><small>{shop.latitude != null && shop.longitude != null ? `Verified location · ${String(shop.city ?? "Finland")}` : "Location has not been verified yet."}</small>
    </form>

    <form className="workspace-form seller-editor-form" onSubmit={(event) => submit(event, (form) => mutate("/api/seller", "POST", { name: field(form, "name"), description: field(form, "description"), imageUrl: field(form, "imageUrl"), price: Number(form.get("price")), categoryId: form.get("categoryId") ? Number(form.get("categoryId")) : null }, "Dish added to your menu."))}>
      <h3>Add a dish</h3><label>Dish name<input name="name" required minLength={2} placeholder="e.g. Sunday roast chicken"/></label><label>Description<input name="description" placeholder="What makes it lovely?"/></label><label>Price (€)<input name="price" type="number" step="0.01" min="0.5" max="500" required placeholder="12.50"/></label><label>Dish image URL<input name="imageUrl" type="url" placeholder="https://…"/></label><label>Category<select name="categoryId" defaultValue=""><option value="">No category</option>{categories.map((category) => <option key={String(category.id)} value={String(category.id)}>{String(category.name)}</option>)}</select></label><OriginButton type="submit" loading={busy} loadingText="Adding…">Add dish <span>+</span></OriginButton>
    </form>

    <form className="workspace-form seller-editor-form seller-category-form" onSubmit={(event) => submit(event, (form) => mutate("/api/seller", "POST", { action: "create-category", name: field(form, "name"), description: field(form, "description"), imageUrl: field(form, "imageUrl") }, "Menu category created."))}>
      <h3>Menu categories</h3><label>Category name<input name="name" required minLength={2} placeholder="Curries, breads…"/></label><label>Short description<input name="description" placeholder="Optional"/></label><label>Category image URL<input name="imageUrl" type="url" placeholder="https://…"/></label><OriginButton type="submit" variant="secondary" loading={busy}>Add category <span>+</span></OriginButton>
      {categories.length ? <div className="workspace-list">{categories.map((category) => <article className="workspace-card workspace-row" key={String(category.id)}><div><b>{String(category.name)}</b><span>{items.filter((item) => Number(item.categoryId) === Number(category.id)).length} dishes</span></div><button type="button" disabled={busy} onClick={() => { const name = window.prompt("Category name", String(category.name)); if (name === null) return; const imageUrl = window.prompt("Category image URL (leave blank to clear)", String(category.imageUrl ?? "")); if (imageUrl === null) return; void mutate("/api/seller", "PATCH", { action: "update-category", categoryId: category.id, name, imageUrl }, "Category updated."); }}>Edit</button><button type="button" className="confirm-danger" disabled={busy} onClick={() => setConfirm({ title: `Remove ${String(category.name)}?`, action: async () => { await mutate("/api/seller", "PATCH", { action: "delete-category", categoryId: category.id }, "Category removed."); } })}>Remove</button></article>)}</div> : <p className="workspace-muted">No categories yet. Add one to organize your menu.</p>}
    </form>

    <div className="workspace-list seller-menu-list"><h3>Your dishes</h3>{items.length ? items.map((item) => <form className="workspace-card seller-dish-editor" key={String(item.id)} onSubmit={(event) => submit(event, (form) => mutate("/api/seller", "PATCH", { itemId: item.id, name: field(form, "name"), description: field(form, "description"), price: Number(form.get("price")), imageUrl: field(form, "imageUrl"), categoryId: form.get("categoryId") ? Number(form.get("categoryId")) : null, isAvailable: form.get("isAvailable") === "on" }, "Dish changes saved."))}>
      <div className="workspace-card-top"><div><b>{String(item.name)}</b><span>{money(item.price)} · {item.isAvailable ? "Available" : "Paused"}</span></div></div><label>Dish name<input name="name" required defaultValue={String(item.name)}/></label><label>Description<input name="description" defaultValue={String(item.description ?? "")}/></label><div className="seller-dish-fields"><label>Price (€)<input name="price" type="number" step="0.01" min="0.5" max="500" defaultValue={String(item.price)}/></label><label>Category<select name="categoryId" defaultValue={String(item.categoryId ?? "")}><option value="">No category</option>{categories.map((category) => <option key={String(category.id)} value={String(category.id)}>{String(category.name)}</option>)}</select></label></div><label>Dish image URL<input name="imageUrl" type="url" placeholder="https://…" defaultValue={String(item.imageUrl ?? "")}/></label><label className="seller-availability"><input type="checkbox" name="isAvailable" defaultChecked={Boolean(item.isAvailable)}/> Available to order</label><div className="workspace-actions"><OriginButton type="submit" variant="secondary" loading={busy}>Save dish</OriginButton><button type="button" disabled={busy} className="confirm-danger" onClick={() => setConfirm({ title: `Remove ${String(item.name)} from your menu?`, action: async () => { await mutate(`/api/seller?itemId=${String(item.id)}`, "DELETE", {}, "Dish removed from the menu."); } })}>Remove dish</button></div>
    </form>) : <p className="workspace-muted">Your kitchen menu is empty. Add the first dish above.</p>}</div>

    <form className="workspace-form seller-editor-form" onSubmit={(event) => submit(event, (form) => mutate("/api/subscriptions", "POST", { action: "create-plan", name: field(form, "name"), description: field(form, "description"), type: field(form, "type"), price: Number(form.get("price")), mealsPerPeriod: Number(form.get("mealsPerPeriod")), menuItemIds: form.getAll("menuItemIds").map(Number) }, "Meal plan published."))}>
      <h3>Publish a meal plan</h3><label>Plan name<input name="name" required minLength={3}/></label><label>Description<input name="description"/></label><label>Billing period<select name="type"><option value="DAILY">Daily</option><option value="THREE_DAY">3 day</option><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option></select></label><label>Price (€)<input name="price" type="number" step="0.01" min="1" max="2000" required/></label><label>Meals per billing period<input name="mealsPerPeriod" type="number" min="1" max="31" defaultValue="5"/></label><fieldset className="meal-plan-dish-options"><legend>Dishes included in every delivery</legend>{items.filter((item) => Boolean(item.isAvailable)).map((item) => <label key={String(item.id)}><input type="checkbox" name="menuItemIds" value={String(item.id)}/><span>{String(item.name)}</span></label>)}</fieldset><OriginButton type="submit" variant="promotional" loading={busy} loadingText="Publishing…">Publish plan <span>→</span></OriginButton>
      {plans.length ? <div className="workspace-list">{plans.map((plan) => <article className="workspace-card workspace-row" key={String(plan.id)}><div><b>{String(plan.name)}</b><span>{money(plan.price)} / {String(plan.type).toLowerCase()} · {plan.isActive ? "Published" : "Hidden"}</span><small>{rows(plan.items).length} included dishes</small></div><button type="button" disabled={busy} onClick={() => { const name = window.prompt("Plan name", String(plan.name)); if (name === null) return; const price = window.prompt("Price per period (€)", String(plan.price)); if (price === null) return; const description = window.prompt("Plan description", String(plan.description ?? "")); if (description === null) return; void mutate("/api/subscriptions", "PATCH", { planId: plan.id, name, price: Number(price), description }, "Meal plan updated."); }}>{plan.isActive ? "Edit plan" : "Edit hidden plan"}</button><button type="button" disabled={busy} onClick={() => void mutate("/api/subscriptions", "PATCH", { planId: plan.id, isActive: !plan.isActive }, plan.isActive ? "Meal plan hidden." : "Meal plan published.")}>{plan.isActive ? "Hide plan" : "Publish plan"}</button><details className="plan-dish-editor"><summary>Included dishes</summary><form className="workspace-form" onSubmit={(event) => submit(event, (form) => mutate("/api/subscriptions", "PATCH", { planId: plan.id, menuItemIds: form.getAll("menuItemIds").map(Number) }, "Meal plan dishes updated."))}>{items.filter((item) => Boolean(item.isAvailable)).map((item) => <label key={String(item.id)}><span><input type="checkbox" name="menuItemIds" value={String(item.id)} defaultChecked={rows(plan.items).some((entry) => Number(entry.menuItemId) === Number(item.id))}/> {String(item.name)}</span></label>)}<OriginButton type="submit" variant="secondary" loading={busy}>Save included dishes</OriginButton></form></details></article>)}</div> : <p className="workspace-muted">No meal plans yet.</p>}
    </form>
    {confirm && <div className="modal-backdrop" role="presentation" onClick={() => setConfirm(null)}><section className="confirm-modal" role="alertdialog" aria-modal="true"><span className="eyebrow">PLEASE CONFIRM</span><h2>{confirm.title}</h2><p>Dishes associated with order history are retained and hidden, so customer order records remain intact.</p><div className="confirm-actions"><button type="button" onClick={() => setConfirm(null)}>Keep it</button><button type="button" className="confirm-danger" onClick={() => { const action = confirm.action; setConfirm(null); void action(); }}>Confirm removal</button></div></section></div>}
  </section>;
}
