/* eslint-disable @typescript-eslint/no-require-imports */
const {chromium,expect}=require('@playwright/test');
(async()=>{const browser=await chromium.launch({channel:'msedge'});try{const c=await browser.newContext({reducedMotion:'reduce'});const p=await c.newPage();await p.addInitScript(()=>localStorage.setItem('home-foods-cookie-choice','accepted'));
 await p.goto('http://localhost:3000/');await p.getByRole('button',{name:'Open navigation menu'}).click();await p.getByRole('button',{name:'Switch to dark mode'}).click();await p.getByRole('dialog').getByRole('link',{name:'Explore Kitchens',exact:true}).click();await expect(p).toHaveURL(/#home-sections$/);await p.getByRole('button',{name:'Open navigation menu'}).click();await expect(p.getByRole('dialog').getByRole('link',{name:'Explore Kitchens',exact:true})).toHaveAttribute('aria-current','page');await p.keyboard.press('Escape');
 for(const route of ['/signin','/join','/forgot-password','/reset-password','/account-recovery']){await p.goto('http://localhost:3000'+route);await expect(p.locator('.app-header')).toHaveCount(0);await expect(p.locator('html')).toHaveAttribute('data-theme','dark');}
 await p.goto('http://localhost:3000/collections/featured');await p.getByRole('textbox',{name:'Search all of HomeFoods'}).fill('Biryani');await p.getByRole('textbox',{name:'Search all of HomeFoods'}).press('Enter');await expect(p.getByRole('combobox',{name:'Search all of HomeFoods'})).toHaveValue('Biryani');
 await p.setViewportSize({width:390,height:844});await p.getByRole('button',{name:'Open navigation menu'}).click();await p.mouse.move(280,360);await p.mouse.down();await p.mouse.move(120,360,{steps:10});await p.mouse.up();await expect(p.getByRole('dialog',{name:'HomeFoods navigation'})).toHaveCount(0);
 console.log('PASS guest hash active-state, dedicated auth layouts, dark persistence, cross-page search, mobile swipe and reduced motion');await c.close();}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exitCode=1});

