import dotenv from 'dotenv';dotenv.config({path:'.env.local',quiet:true});dotenv.config({quiet:true});Object.assign(process.env,{NODE_ENV:'development'});
import assert from 'node:assert/strict';
import {createHmac,randomUUID} from 'node:crypto';
import {mkdir,unlink,readdir,readFile} from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {chromium,expect} from '@playwright/test';
const {db}=await import('../src/prisma/db');const {getSessionSigningSecret}=await import('../src/lib/session-secret');const {isNationwideDevelopmentMode}=await import('../src/lib/feature-flags');assert.ok(isNationwideDevelopmentMode());
const base='http://localhost:3000',suffix=randomUUID().slice(0,8),users:number[]=[],shops:number[]=[],uploaded:string[]=[];
const browser=await chromium.launch({channel:'chrome',headless:true});
await mkdir('artifacts/image-uploads',{recursive:true});
try{
 const seller=await db.orm.public.User.create({email:`upload-${suffix}@homefoods.test`,name:'[TEST] Upload seller',password:'disabled-test-login',role:'SELLER'});users.push(seller.id);
 const shop=await db.orm.public.Shop.create({sellerId:seller.id,name:`[TEST] Upload kitchen ${suffix}`,status:'ACTIVE',isOnline:true,address:'[SANDBOX LOCATION] Helsinki',city:'Helsinki',latitude:60.1699,longitude:24.9384});shops.push(shop.id);
 const other=await db.orm.public.User.create({email:`upload-other-${suffix}@homefoods.test`,name:'[TEST] Other seller',password:'disabled-test-login',role:'SELLER'});users.push(other.id);const otherShop=await db.orm.public.Shop.create({sellerId:other.id,name:'[TEST] Other kitchen'});shops.push(otherShop.id);
 const context=await browser.newContext();const payload=Buffer.from(JSON.stringify({userId:seller.id,role:'SELLER',email:seller.email,name:seller.name,authVersion:0,expiresAt:Math.floor(Date.now()/1000)+3600})).toString('base64url');await context.addCookies([{name:'home-foods-session',value:`${payload}.${createHmac('sha256',getSessionSigningSecret()).update(payload).digest('base64url')}`,url:base,httpOnly:true,sameSite:'Lax'}]);
 const png=await sharp({create:{width:800,height:600,channels:3,background:'#ce7029'}}).png().toBuffer();
 for(const format of ['jpeg','png','webp'] as const){const data=await sharp(png).toFormat(format).toBuffer();const res=await context.request.post(base+'/api/uploads',{data,headers:{Origin:base,'Content-Type':`image/${format}`}});assert.equal(res.status(),201,await res.text());const ref=(await res.json()).imageUrl;uploaded.push(ref);const media=await context.request.get(base+ref);assert.equal(media.status(),200);assert.equal(media.headers()['content-type'],'image/webp');assert.equal((await sharp(await media.body()).metadata()).width,800);}
 const guest=await browser.newContext();assert.equal((await guest.request.post(base+'/api/uploads',{data:png})).status(),401);
 assert.equal((await context.request.post(base+'/api/uploads',{data:png,headers:{Origin:'https://foreign.test'}})).status(),403);
 for(const bytes of [Buffer.alloc(0),Buffer.from('corrupt image'),Buffer.alloc(8*1024*1024+1)])assert.ok([413,422].includes((await context.request.post(base+'/api/uploads',{data:bytes,headers:{Origin:base}})).status()));
 const foreignItem=await db.orm.public.MenuItem.create({shopId:otherShop.id,name:'Foreign dish',price:5});
 assert.equal((await context.request.patch(base+'/api/seller',{data:{itemId:foreignItem.id,imageUrl:uploaded[0]},headers:{Origin:base}})).status(),404);
 assert.equal((await context.request.post(base+'/api/seller',{data:{name:'Denied reference',price:5,imageUrl:uploaded[0].replace(`/media/${shop.id}/`,`/media/${otherShop.id}/`)},headers:{Origin:base}})).status(),403);
 const p=await context.newPage();await p.goto(base+'/workspace#seller-menu');const add=p.locator('form').filter({has:p.getByRole('heading',{name:'Add a dish',exact:true})});await expect(add).toBeVisible({timeout:45000});await add.getByLabel('Dish name',{exact:true}).fill(`Upload dish ${suffix}`);await add.getByLabel('Price (€)',{exact:true}).fill('8');
 const control=add.locator('.image-upload');const chooser=p.waitForEvent('filechooser');await control.getByRole('button',{name:'Upload image',exact:true}).click();await (await chooser).setFiles({name:'dish.png',mimeType:'image/png',buffer:png});await expect(control.locator('img')).toBeVisible();
 await control.getByRole('button',{name:'Discard selection'}).click();await control.locator('input[type=file]').first().setInputFiles({name:'unsafe.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});await expect(control.getByRole('alert')).toContainText('JPG, PNG or WebP');await control.getByRole('button',{name:'Discard selection'}).click();
 const transfer=await p.evaluateHandle((bytes:number[])=>{const dt=new DataTransfer();dt.items.add(new File([new Uint8Array(bytes)],'dropped.png',{type:'image/png'}));return dt;},[...png]);await control.locator('.image-drop').dispatchEvent('drop',{dataTransfer:transfer});await expect(control.locator('img')).toBeVisible();await transfer.dispose();await expect(control.locator('input[capture]')).toHaveAttribute('capture','environment');

 await add.getByRole('button',{name:/Add dish/}).click();assert.equal(await db.orm.public.MenuItem.where({shopId:shop.id}).first(),null,'unconfirmed selection must not save');
 await p.route('**/api/uploads',route=>route.abort('failed'));await control.getByRole('button',{name:'Confirm & upload'}).click();await expect(control.getByRole('alert')).toContainText('Upload failed');await expect(add.getByLabel('Dish name',{exact:true})).toHaveValue(`Upload dish ${suffix}`);await p.unroute('**/api/uploads');await control.getByRole('button',{name:'Retry upload'}).click();await expect(control.locator('.image-status')).toContainText('Upload complete',{timeout:30000});await add.getByRole('button',{name:/Add dish/}).click();await expect(p.getByText('Dish added to your menu.',{exact:true})).toBeVisible();
 let item=await db.orm.public.MenuItem.where({shopId:shop.id}).first();assert.ok(item?.imageUrl);uploaded.push(item.imageUrl);
 const edit=p.locator('.seller-dish-editor').filter({hasText:`Upload dish ${suffix}`});
 for(const width of [390,1440]){await p.setViewportSize({width,height:950});for(const theme of ['light','dark']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await edit.scrollIntoViewIfNeeded();await p.screenshot({path:`artifacts/image-uploads/${width}-${theme}.png`});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}}
 await p.reload();await expect(p.locator('.seller-dish-editor img')).toHaveAttribute('src',item.imageUrl);
 const api=await guest.request.get(base+`/api/catalog?q=${encodeURIComponent(`Upload dish ${suffix}`)}`);assert.ok((await api.text()).includes(item.imageUrl));
 const customer=await guest.newPage();await customer.goto(base+`/kitchens/${shop.id}`);await expect(customer.locator(`img[src="${item.imageUrl}"]`).first()).toBeVisible();
 await customer.getByRole('button',{name:'Add '+item.name+' to cart',exact:true}).click();await customer.getByRole('button',{name:/^Open cart/}).click();await expect(customer.getByRole('dialog',{name:'Your basket'}).locator('img')).toHaveAttribute('src',item.imageUrl);await customer.getByRole('button',{name:'Close basket'}).click();
 const old=item.imageUrl;await edit.locator('input[type=file]').first().setInputFiles({name:'replacement.webp',mimeType:'image/webp',buffer:await sharp(png).webp().toBuffer()});await edit.getByRole('button',{name:'Confirm & upload'}).click();await expect(edit.locator('.image-status')).toContainText('Upload complete',{timeout:30000});await edit.getByRole('button',{name:'Save dish',exact:true}).click();await expect(p.getByText('Dish changes saved.',{exact:true})).toBeVisible();item=await db.orm.public.MenuItem.where({id:item.id}).first();assert.ok(item?.imageUrl&&item.imageUrl!==old);uploaded.push(item.imageUrl);assert.equal((await guest.request.get(base+old)).status(),200,'old file retained until safe cleanup');
 await customer.reload();await expect(customer.locator(`img[src="${item.imageUrl}"]`).first()).toBeVisible();await customer.getByRole('button',{name:/^Open cart/}).click();await expect(customer.getByRole('dialog',{name:'Your basket'}).locator('img')).toHaveAttribute('src',item.imageUrl);await customer.getByRole('button',{name:'Close basket'}).click();
 p.once('dialog',d=>d.accept());await edit.getByRole('button',{name:'Remove image',exact:true}).click();await edit.getByRole('button',{name:'Save dish',exact:true}).click();await expect(edit.locator('input[name=imageUrl]')).toHaveValue('');await expect.poll(async()=>(await db.orm.public.MenuItem.where({id:item!.id}).first())?.imageUrl).toBe('');await customer.reload();await expect(customer.locator('.kitchen-item-image img')).not.toHaveAttribute('src',item.imageUrl!);await expect.poll(()=>customer.locator('.kitchen-item-image img').evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);

 const profile=p.locator('#kitchen-profile-fields form');if(!await profile.isVisible())await p.getByRole('button',{name:/Kitchen Profile/}).click();
 for(const label of ['Kitchen logo','Kitchen cover image']){const uploader=profile.locator('.image-upload').filter({has:p.locator('strong',{hasText:label})});await uploader.locator('input[type=file]').first().setInputFiles({name:'profile.png',mimeType:'image/png',buffer:png});await uploader.getByRole('button',{name:'Confirm & upload'}).click();await expect(uploader.locator('.image-status')).toContainText('Upload complete');}
 await profile.getByRole('button',{name:'Save kitchen profile',exact:true}).click();await expect(p.getByText('Kitchen profile saved.',{exact:true})).toBeVisible();const savedShop=await db.orm.public.Shop.where({id:shop.id}).first();assert.ok(savedShop?.logoUrl?.startsWith('/api/media/')&&savedShop.coverImageUrl?.startsWith('/api/media/'));await customer.reload();await expect(customer.locator('.kitchen-identity-logo img')).toHaveAttribute('src',savedShop!.logoUrl!);
 const buyer=await db.orm.public.User.create({email:'upload-buyer-'+suffix+'@homefoods.test',name:'[TEST] Upload buyer',password:'disabled-test-login',role:'CUSTOMER'});users.push(buyer.id);const cp=Buffer.from(JSON.stringify({userId:buyer.id,role:'CUSTOMER',email:buyer.email,name:buyer.name,authVersion:0,expiresAt:Math.floor(Date.now()/1000)+3600})).toString('base64url');await guest.addCookies([{name:'home-foods-session',value:cp+'.'+createHmac('sha256',getSessionSigningSecret()).update(cp).digest('base64url'),url:base,httpOnly:true,sameSite:'Lax'}]);
 await context.request.patch(base+'/api/seller',{data:{itemId:item!.id,imageUrl:uploaded[0]},headers:{Origin:base}});assert.equal((await guest.request.post(base+'/api/favorites',{data:{menuItemId:item!.id},headers:{Origin:base}})).status(),200);await customer.goto(base+'/favorites');await expect(customer.locator('img[src="'+uploaded[0]+'"]').first()).toBeVisible();await customer.goto(base+'/?q='+encodeURIComponent(item!.name));await expect(customer.locator('img[src="'+uploaded[0]+'"]').first()).toBeVisible();
 console.log('PASS: JPG/PNG/WebP uploads; public retrieval; corrupt/empty/oversize and origin/ownership rejection; native chooser event and desktop drop; preview/confirmation; failed upload retry with draft retained; create/replace/remove; database/reload persistence; catalog, kitchen, basket, favourites, search and logo/cover persistence; desktop/mobile light/dark layout. Native mobile camera and physical Apple/Android devices not tested.');
}catch(error){console.error(error instanceof Error?error.message.split('Call log:')[0].replace(/home-foods-session=[^\s'"]+/g,'home-foods-session=[redacted]'):'Upload verification failed.');process.exitCode=1;}finally{
 for(const uid of users)for(const f of await db.orm.public.Favorite.where({customerId:uid}).all())await db.orm.public.Favorite.where({id:f.id}).delete();
 for(const id of shops){for(const item of await db.orm.public.MenuItem.where({shopId:id}).all())await db.orm.public.MenuItem.where({id:item.id}).delete();await db.orm.public.Shop.where({id}).delete();const dir=path.resolve('.data/uploads',String(id));if(dir.startsWith(path.resolve('.data/uploads')+path.sep)){for(const file of await readdir(dir).catch(()=>[]))if(/^[a-f0-9-]+\.webp$/.test(file))await unlink(path.join(dir,file));}}
 for(const id of users)await db.orm.public.User.where({id}).delete();
 const cleanup=path.resolve('.data/uploads/cleanup');for(const file of await readdir(cleanup).catch(()=>[])){if(!file.endsWith('.json'))continue;const entry=JSON.parse(await readFile(path.join(cleanup,file),'utf8'));if(shops.some(id=>entry.reference.startsWith(`/api/media/${id}/`)))await unlink(path.join(cleanup,file));}
 await browser.close();await db.close();
}
