import dotenv from 'dotenv';dotenv.config({path:'.env.local',quiet:true});dotenv.config({quiet:true});Object.assign(process.env,{NODE_ENV:'development'});
import assert from 'node:assert/strict';import {createHmac,randomUUID} from 'node:crypto';import {chromium,expect} from '@playwright/test';
const {db}=await import('../src/prisma/db');const {getSessionSigningSecret}=await import('../src/lib/session-secret');const {isNationwideDevelopmentMode}=await import('../src/lib/feature-flags');assert.ok(isNationwideDevelopmentMode());
const base='http://localhost:3000',suffix=randomUUID().slice(0,8),ids:number[]=[];let shopId=0;const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const users=[];for(const role of ['ADMIN','SELLER','RIDER'] as const){const user=await db.orm.public.User.create({email:`verify-${role.toLowerCase()}-${suffix}@homefoods.test`,name:`[TEST] Verification ${role}`,password:'disabled-test-login',role});ids.push(user.id);users.push(user);}
 const [admin,seller,riderUser]=users;const rider=await db.orm.public.Rider.create({userId:riderUser.id,isAvailable:false});const shop=await db.orm.public.Shop.create({sellerId:seller.id,name:`[TEST] Verification kitchen ${suffix}`,status:'PENDING',isOnline:false,address:'[SANDBOX LOCATION] Mannerheimintie 9, Helsinki',city:'Helsinki',latitude:60.1699,longitude:24.9384});shopId=shop.id;
 const context=await browser.newContext();const payload=Buffer.from(JSON.stringify({userId:admin.id,role:'ADMIN',email:admin.email,name:admin.name,authVersion:0,expiresAt:Math.floor(Date.now()/1000)+3600})).toString('base64url');const signature=createHmac('sha256',getSessionSigningSecret()).update(payload).digest('base64url');await context.addCookies([{name:'home-foods-session',value:`${payload}.${signature}`,url:base,httpOnly:true,sameSite:'Lax'}]);
 const p=await context.newPage();await p.goto(`${base}/workspace/admin/kitchens/${shop.id}`);await p.getByRole('button',{name:'Verify kitchen',exact:true}).click();await expect(p.getByText('Kitchen verified.',{exact:true})).toBeVisible({timeout:45000});await expect(p.getByRole('dialog',{name:'Confirm administrative action'})).toHaveCount(0);assert.equal((await db.orm.public.Shop.where({id:shop.id}).first())?.status,'ACTIVE');
 await p.getByLabel(`Actions for ${shop.name}`).click();await p.getByRole('button',{name:'Suspend kitchen',exact:true}).click();let dialog=p.getByRole('dialog',{name:'Confirm administrative action'});await expect(dialog.getByRole('textbox',{name:'Reason / review notes'})).toHaveAttribute('required','');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
 await p.goto(`${base}/workspace/admin/riders/${rider.id}`);await p.getByRole('button',{name:'Verify rider',exact:true}).click();await expect(p.getByText('Rider verified.',{exact:true})).toBeVisible({timeout:30000});await expect(p.getByRole('dialog',{name:'Confirm administrative action'})).toHaveCount(0);assert.equal((await db.orm.public.Rider.where({id:rider.id}).first())?.isVerified,true);
 await p.getByRole('button',{name:'Suspend account',exact:true}).click();dialog=p.getByRole('dialog',{name:'Confirm administrative action'});await expect(dialog.getByRole('textbox',{name:'Reason / review notes'})).toHaveAttribute('required','');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
 for(const [action,id] of [['suspend-kitchen',shop.id],['suspend-account',riderUser.id]] as const){let r=await context.request.patch(base+'/api/admin/operations',{headers:{Origin:base},data:{action,id}});assert.equal(r.status(),422);r=await context.request.patch(base+'/api/admin/operations',{headers:{Origin:base},data:{action,id,reason:'Temporary fixture suspension check'}});assert.equal(r.status(),200);}
 const logs=await db.orm.public.AdminAuditLog.where({actorId:admin.id}).all();assert.equal(logs.length,4);assert.ok(logs.some(a=>a.action==='verify-rider'&&a.reason==='Rider verified by administrator.'));assert.ok(logs.some(a=>a.action==='approve-kitchen'&&a.reason==='Kitchen verified by administrator.'));
 await p.getByRole('button',{name:'Open navigation menu'}).click();const nav=p.getByRole('dialog',{name:'HomeFoods navigation'});await expect(nav.getByRole('link',{name:'Settings',exact:true})).toHaveCount(0);await expect(nav.getByRole('link',{name:/Manage Account/})).toBeVisible();
 console.log('PASS: one-click kitchen/rider verification without comments, audited actor/action, suspension UI and API comment requirements, sidebar Settings removed and Manage Account retained.');
}finally{for(const id of ids){for(const a of await db.orm.public.AdminAuditLog.where({actorId:id}).all())await db.orm.public.AdminAuditLog.where({id:a.id}).delete();}if(shopId)await db.orm.public.Shop.where({id:shopId}).delete();for(const id of ids){await db.orm.public.Rider.where({userId:id}).delete();await db.orm.public.User.where({id}).delete();}await browser.close();await db.close();}
